# Generated by Django 5.1.5 on 2025-02-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_register',
            name='full_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='patient_register',
            name='full_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
