# Generated by Django 5.1.5 on 2025-02-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='meeting_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient_register',
            name='gmail',
            field=models.EmailField(default=2, max_length=254),
            preserve_default=False,
        ),
    ]
