# Generated by Django 5.1.5 on 2025-02-01 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor_register',
            old_name='name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='patient_register',
            old_name='name',
            new_name='full_name',
        ),
    ]
