# Generated by Django 5.1.5 on 2025-02-01 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_doctor_register_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_register',
            name='full_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='patient_register',
            name='full_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
